### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by it-can** [dmitry-ivanov/laravel-console-mutex#12]
Can you support laravel 5.8 for this package?

https://laravel.com/docs/5.8/upgrade

**Comment by dmitry-ivanov** [comment]
Yeah, I have it in my notes.

I'm a bit busy now, will do it on Saturday I hope.

**Comment by dmitry-ivanov** [comment]
Done 🙂 👍 

https://github.com/dmitry-ivanov/laravel-console-mutex/releases/tag/5.8.0
