### ISSUE TITLE
Laravel 6 is released!

### ISSUE THREAD

**Issue by it-can** [dmitry-ivanov/laravel-console-mutex#15]
Laravel 6 is released today!

**Comment by dmitry-ivanov** [comment]
Yeah, I've seen it too, thanks! :)

I'll try to release the new version of the package this week 👍

**Comment by it-can** [comment]
@dmitry-ivanov added a PR https://github.com/dmitry-ivanov/laravel-console-mutex/pull/16

**Comment by dmitry-ivanov** [comment]
@it-can Laravel 6 support added, see release [`6.0.0`](https://github.com/dmitry-ivanov/laravel-console-mutex/releases/tag/6.0.0).

Thanks again! 🙂
