### ISSUE TITLE
Not working in tests

### ISSUE THREAD

**Issue by cezar62882** [dmitry-ivanov/laravel-console-mutex#23]
### Versions:

- Package Version: 7.0.0

- PHP Version: 7.4

### Description:
if you want to run a command in test more than 1 time you get an error than the command is running now 

### Steps to reproduce:
```
<?php
class YourCommandTest extends TestCase
{

    public function testExample()
    {
        $this->artisan('command', ['param' => 'value']);
    }

    public function test2Example()
    {
        $this->artisan('command', ['param' => 'value']); // throw exception
    }
}
```

**Comment by dmitry-ivanov** [comment]
Are you sure that you're not using paratest _(or similar parallel tests execution tool)_, and actually have two commands running at the same time?

**Comment by cezar62882** [comment]
I just run ```php artisan test```

**Comment by dmitry-ivanov** [comment]
@cezar62882 Yep, checked and verified 👍

The reason for that - is that the package does _lock releasing_ in the registered _shutdown function_ _(which is never called when you run tests together)_.

The simplest solution would be to run these tests in the separate processes:

```php
/**
 * @test
 * @runInSeparateProcess
 */
public function example_test_1()
{
    $this->artisan('command', ['param' => 'value']);
}

/**
 * @test
 * @runInSeparateProcess
 */
public function example_test_2()
{
    $this->artisan('command', ['param' => 'value']);
}
```

_PS: See more in the [PHPUnit docs](https://phpunit.readthedocs.io/en/latest/annotations.html#runinseparateprocess). You also might want to consider using the [`@preserveGlobalState`](https://phpunit.readthedocs.io/en/latest/annotations.html#preserveglobalstate), if needed._

**Comment by cezar62882** [comment]
awesome, thanks!
