### ISSUE TITLE
Lock files remain in storage

### ISSUE THREAD

**Issue by anabeto93** [dmitry-ivanov/laravel-console-mutex#27]
### Versions:
- Package Version: #.#.#
- PHP Version: #.#.# 8.1.2

### Description:

This is not exactly BUG but I haven't seen the option to open a discussion. Just a minor change to the docs to indicate it works with `sqlite` too.

Have been able to use it with sqlite while testing and I've noticed the lock files remain when tests are completed. I'm wondering if they'd have to be cleaned up aftewards?

### Evidence
![confirm_mutex_works](https://user-images.githubusercontent.com/7607657/162213143-f082cfee-eb9e-478a-90d1-6770a3792e37.png)

![dynamic_strategy_based_on_env](https://user-images.githubusercontent.com/7607657/162213252-6a8799d7-a604-460a-b96e-3619e36b54f4.png)

![not_deleted_when_done](https://user-images.githubusercontent.com/7607657/162213288-68acc885-9a5d-4290-a010-719ad0e1a019.png)

**Comment by dmitry-ivanov** [comment]
Hi @anabeto93,

> Just a minor change to the docs to indicate it works with sqlite too.

The `sqlite` is not supported.

If you set strategy to `sqlite` _(or any other unknown strategy)_ - it would simply [fall back to the default `file` strategy](https://github.com/dmitry-ivanov/laravel-console-mutex/blob/3327b517332db45f51cad845ed19225fdcef252e/src/Mutex.php#L59-L77).

> Have been able to use it with sqlite while testing and I've noticed the lock files remain when tests are completed. I'm wondering if they'd have to be cleaned up afterward?

No, when you use the `file` strategy _(which you do)_, the lock files remain after releasing the lock.

That's how the underlying lock function works.

See #4 and #8 related to the same question.

Hope it helps!
Thanks!
