### ISSUE TITLE
Error 'Command is running now'

### ISSUE THREAD

**Issue by saha-embedtech** [dmitry-ivanov/laravel-console-mutex#29]
### Versions:

- Package Version: 8.28
- PHP Version: 8.0

### Description:
I am using your package to prevent overlapping command that command runs in loop in every second. Code is working fine but getting an error `Command is running now! {"exception":"[object] (Illuminated\\Console\\MutexRuntimeException(code: 0): Command is running now! at /vendor/illuminated/console-mutex/src/WithoutOverlapping.php:35)` and this one is full the log file.

How is possible to remove the above error? Please guide

**Comment by dmitry-ivanov** [comment]
Just add the try/catch for your call, or [disable reporting](https://laravel.com/docs/master/errors#ignoring-exceptions-by-type) in your `App\Exceptions\Handler` for that exception.
