### ISSUE TITLE
file lock mechanics doesn't work on EFS backed filesystem

### ISSUE THREAD

**Issue by hlorofos** [dmitry-ivanov/laravel-console-mutex#8]
The issue is similar to what already discussed in #4.
It seems like the internal lock module doesn't work properly on AWS EFS filesystem.

Due to lock file is not deleted `laravel-console-mutex` on the next run giving me `Command is running now!` exception. Although we are heard the lock file should not be deleted - in that setup the file is present and locking mechanics is broken.

**Comment by dmitry-ivanov** [comment]
Hi, @hlorofos !

#4 was NOT an issue of the package.

Lock file **SHOULD NOT** be deleted after the command execution. It is the correct behavior.

File strategy is using [flock php function](http://php.net/manual/en/function.flock.php).

So, you get your exception for some other reason.

I've searched a bit, and it looks like it is a limitation of your FS (AWS EFS):
https://ops.tips/blog/limits-aws-efs-nfs-locks/
https://www.jeffgeerling.com/blog/2018/getting-best-performance-out-amazon-efs
https://aws.amazon.com/ru/about-aws/whats-new/2017/03/amazon-elastic-file-system-amazon-efs-now-supports-nfsv4-lock-upgrading-and-downgrading/

My suggestions for your case:
1) Try to use the same code on a local `storage` (it should work fine);
2) If it does, then we know that the problem in your case relates to your FS. Use another mutex strategy, for example, `mysql`.

https://github.com/dmitry-ivanov/laravel-console-mutex#strategies
